version: '3.8'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: knowledgehub
      POSTGRES_USER: khubuser
      POSTGRES_PASSWORD: khubpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
volumes:
  pgdata:
